apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-automation-demo-jakub
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-jakub
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-jakub
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo-jakub
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo-jakub
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo-jakub
    notifications.argoproj.io/subscribe.on-sync-status-running.slack: argo-jakub
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: chart
      repoURL: https://github.com/JKIPIKA/demo-cicd-automation-app.git
      targetRevision: main
    - path: manifests
      repoURL: https://github.com/JKIPIKA/argocd-multisource-test.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  sources:
  - repoURL: https://github.com/JKIPIKA/demo-cicd-automation-app.git
    path: common
    targetRevision: main
    helm:
      valueFiles:
      - ../cluster/cluster_values.yaml
      - $values/env_override.yaml
  - repoURL: https://github.com/JKIPIKA/argocd-multisource-test/tree/main
    targetRevision: main
    ref: values
