apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  slack-token: eG94Yi03MTY4ODMzNzQxMDQyLTcyMDM5MjAxNDM5MzgtSHd4SnRBQjB1UmwxTHdDZDczSnJYdnJC
type: Opaque